ShopMVC/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Entities;
using DataAccess.Data;
using Microsoft.AspNetCore.Authorization;
using BusinessLogic.Interfaces;
using BusinessLogic.Services;
using BusinessLogic.DTOs;

namespace ShopMVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly ICategoriesService _categoriesService;

        public CategoriesController(ICategoriesService categoriesService)
        {
            _categoriesService = categoriesService;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            List<CategoryDTO> categories = await _categoriesService.GetAll();
            return View(categories);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            var category = await _categoriesService.Get((int)id);
            return View(category);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] CategoryDTO categoryDTO)
        {
            if (ModelState.IsValid)
            {
                await _categoriesService.Create(categoryDTO);
                return RedirectToAction(nameof(Index));
            }
            return View(categoryDTO);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || await _categoriesService.GetAll() == null)
            {
                return NotFound();
            }

            var category = await _categoriesService.Get((int)id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] CategoryDTO categoryDTO)
        {
            await _categoriesService.Update(categoryDTO);
            return View(categoryDTO);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            var category = await _categoriesService.Get((int)id);
            return View(category);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await _categoriesService.GetAll() == null)
            {
                return Problem("Entity set 'ShopMVCContext.Category'  is null.");
            }
            var category = await _categoriesService.Get((int)id);
            if (category != null)
            {
                await _categoriesService.Delete(category.Id);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ShopMVC/Controllers/OrderController.cs
using BusinessLogic.Interfaces;
using BusinessLogic.Services;
using DataAccess.Data;
using DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.EntityFrameworkCore;
using Org.BouncyCastle.Crypto.Macs;
using ShopMVC.Helper;
using ShopMVC.Interfaces;
using ShopMVC.Models;
using System.Security.Claims;
using System.Text;
using System.Text.Json;

namespace ShopMVC.Controllers
{
    public class OrderController : Controller
    {
        private readonly IProductsService _productsService;
        private readonly IOrdersService _ordersService;
        private readonly IStorageService _storageService;
        private readonly IMailService _mailService;
        public OrderController(IOrdersService cordersService, IProductsService productsService, IStorageService storageService, IMailService mailService)
        {
            _ordersService = cordersService;
            _productsService = productsService;
            _storageService = storageService;
            _mailService = mailService;
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var viewModel = await _ordersService.GetAll();
            return View(viewModel);
        }
        public async Task<IActionResult> CreateOrder(List<int> productId, List<int> quantity)
        {
            await _ordersService.CreateAsync();
            await _storageService.UpdateQuantityDecrease(productId, quantity);

            var userEmail = HttpContext.User.Identity.Name;
            var body = _ordersService.CreateBodyAsync().Result;
            var subject = await _ordersService.ViewOrderAsync();
            await _mailService.SendMailAsync(subject, body, userEmail!);

            HttpContext.Session.Remove("mycart");
            return RedirectToAction(nameof(Index));
        }
    }
}

ShopMVC/Controllers/ProductController.cs
using BusinessLogic.DTOs;
using BusinessLogic.Interfaces;
using BusinessLogic.Services;
using DataAccess.Data;
using DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopMVC.Models;

namespace ShopMVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IProductsService _productsService;
        private readonly ICategoriesService _categoriesService;
        private readonly IStorageService _storageService;

        public ProductController(IProductsService productsService, ICategoriesService categoriesService, IStorageService storageService)
        {
            _productsService = productsService;
            _categoriesService = categoriesService;
            _storageService = storageService;
            _storageService = storageService;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            List<CategoryDTO> categories= await _categoriesService.GetAll();
            ViewBag.ListCategories = categories;
            ViewData["ListCategories"] = categories;
            var products = await _productsService.GetAll();
            return View(products);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id, string returnUrl = null) 
        {
            var product = await _productsService.Get(id);
            if (product == null) return NotFound();
            ViewBag.ReturnUrl = returnUrl;

            var productCartViewModel = new ProductCartViewModel
            {
                Product = product,
                StorageQuantity = GetStorageQuantityForProduct(product.Id)
            };
            return View(productCartViewModel);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            await _productsService.Delete((int)id);
            return RedirectToAction(nameof(Index), "Home");
        }
        [HttpGet]
        public async Task<IActionResult> Create() {
            var categories = await _categoriesService.GetAll();
            ViewBag.ListCategory = new SelectList(categories,"Id","Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateProductDTO createproductDTO)
        {
            if (!ModelState.IsValid)
            {
                var categories = await _categoriesService.GetAll();
                ViewBag.ListCategory = new SelectList(categories, "Id", "Name");
                return View(createproductDTO);
            }
            await _productsService.Create(createproductDTO);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id) {

            var product = await _productsService.Get(id);
            if (product != null)
            {
                var categories = await _categoriesService.GetAll();
                ViewBag.ListCategory = new SelectList(categories, "Id", "Name", product.CategoryId);
                return View(product);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(ProductDTO ProductDTO)
        {
            await _productsService.Update(ProductDTO);
            return RedirectToAction("Index");
        }
        private int GetStorageQuantityForProduct(int productId)
        {
            var quantity = _storageService.GetStorageQuantityForProduct(productId);
            if (quantity != null)
            {
                return quantity.Result;
            }
            return 0;
        }
    }
}

ShopMVC/Controllers/StorageController.cs
using BusinessLogic.Interfaces;
using DataAccess.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopMVC.Helper;
using ShopMVC.Models;

namespace ShopMVC.Controllers
{
    public class StorageController : Controller
    {
        private readonly IProductsService _productsService;
        private readonly ICategoriesService _categoriesService;
        private readonly IStorageService _storageService;

        public StorageController(IProductsService productsService, ICategoriesService categoriesService, IStorageService storageService)
        {
            _productsService = productsService;
            _categoriesService = categoriesService;
            _storageService = storageService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var products = await _productsService.GetAll();
            var productsCartViewModel = products.Select(p => new ProductCartViewModel
            {
                Product = p,
                IsInCart = IsProductInCart(p.Id),
                StorageQuantity = GetStorageQuantityForProduct(p.Id)
            }).ToList();

            return View(productsCartViewModel);

        }
        [HttpPost]
        public async Task<IActionResult> UpdateQuantity(int productId, int quantity)
        {
            var product = await _storageService.UpdateQuantity(productId, quantity);
            return RedirectToAction("Index", product);   
        }
        private bool IsProductInCart(int id)
        {
            Dictionary<int, int> IdCount = HttpContext.Session.GetObject<Dictionary<int, int>>("mycart");
            if (IdCount == null) return false;
            return IdCount.ContainsKey(id);
        }
        private int GetStorageQuantityForProduct(int productId)
        {
            var quantity = _storageService.GetStorageQuantityForProduct(productId);
            if (quantity != null )
            {
                return quantity.Result;
            }
            return 0; 
        }
    }
}

ShopMVC/Views/Shared/_CardProductPartial.cshtml
@model ProductCartViewModel
@{
    string productImagePlaceholder = @"https://www.freeiconspng.com/thumbs/no-image-icon/no-image-icon-15.png";
}
<link rel="stylesheet" href="~/css/cardProduct.css" />
<div class="col-sm-3 mb-4">
    <a href="@Url.Action("Details", "Product", new { id = Model.Product.Id })" class="card-link" style="text-decoration: none; color: inherit;">
        <div class="card product-card" style=" height: 350px" onmouseover="zoomIn(this)" onmouseout="zoomOut(this)">
            <div class="product-card-img mt-4">
                <img src="@(Model.Product.ImagePath ?? productImagePlaceholder)" class="card-img-top" alt="...">
            </div>
            <div class="card-body">
                <p class="card-title" style="font-size: 12px;">@Model.Product.Name</p>
                <p class="card-title" style="font-size: 12px;">
                    @if (Model.StorageQuantity > 0)
                    {
                        <span style="color: green;">The product is available</span>
                    }
                    else
                    {
                        <span style="color: red;">The product is not available</span>
                    }

                </p>
            </div >
            <div class="card-body d-flex flex-column justify-content-end">

                <h5><span class="badge bg-primary d-flex  align-text-bottom">@string.Format("{0:N}",Model.Product.Price) ₴</span></h5>



            </div>

@*                @if (!Model.IsInCart)
                {
                    <a asp-controller="Cart" asp-action="Add" asp-route-id=@Model.Product.Id class="btn btn-danger">Add To Cart</a>
                }
                else
                {
                    <a asp-controller="Cart" asp-action="Remove" asp-route-id=@Model.Product.Id class="btn btn-secondary">Delete From Cart</a>
                }*@
        </div>
    </a>
</div>

<script src="~/js/cardProduct.js"></script>

ShopMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 @*fixed-top*@">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShopMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        @if (@User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Storage" asp-action="Index">Storage</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                            </li>
                        }
                        <li class="nav-item">
                            @{
                                var listProductInCart = Context.Session.GetObject<Dictionary<int, int>>("mycart");
                                var res = 0;
                                if (listProductInCart != null)
                                {

                                    foreach (var key in listProductInCart.Keys)
                                    {
                                        res += listProductInCart[key];
                                    }
                                }
                            }

                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                                Cart <i class="bi bi-cart4"></i> @(res)
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>